import asyncio
from contextlib import asynccontextmanager

import redis.asyncio as redis
from fastapi import FastAPI, HTTPException, Request, status
from fastapi.encoders import jsonable_encoder
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse

from app.api.routes import assets, health, marketdata, markets
from app.core.config import settings
from app.core.event_bus import EventBus
from app.core.logging import configure_logging, get_logger
from app.core.workers import candle_consumer_loop, dlq_maintenance_loop, producer_loop
from app.middleware.request_id import RequestIDMiddleware
from app.middleware.security_headers import SecurityHeadersMiddleware

configure_logging()
log = get_logger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    log.info("service_starting", environment=settings.ENVIRONMENT, service=settings.SERVICE_NAME)

    redis_client = redis.from_url(settings.REDIS_URL, decode_responses=True)
    event_bus = EventBus(redis_client)
    app.state.redis_client = redis_client
    app.state.event_bus = event_bus

    stop_event = asyncio.Event()
    background_tasks: list[asyncio.Task] = []

    if settings.SIMULATOR_ENABLED:
        background_tasks = [
            asyncio.create_task(producer_loop(event_bus, stop_event), name="producer_loop"),
            asyncio.create_task(candle_consumer_loop(event_bus, stop_event), name="candle_consumer_loop"),
            asyncio.create_task(dlq_maintenance_loop(event_bus, stop_event), name="dlq_maintenance_loop"),
        ]
        log.info("background_workers_started", count=len(background_tasks))
    else:
        log.info("simulator_disabled")

    yield

    stop_event.set()
    for task in background_tasks:
        task.cancel()
    for task in background_tasks:
        try:
            await task
        except (asyncio.CancelledError, Exception):
            pass

    await redis_client.aclose()
    log.info("service_stopping", service=settings.SERVICE_NAME)


app = FastAPI(
    title="Exchange Market Data Service",
    description="Assets, markets, ticker, candles, recent trades, and order "
    "book snapshots. Phase 3: trade/order-book data is generated by a "
    "deterministic paper-data simulator (see app/core/simulator.py) since "
    "there is no matching engine yet (phase 4) -- the data flows through "
    "the real backend pipeline (Postgres + Redis Streams event bus), it is "
    "not mocked in the frontend.",
    version="0.1.0",
    docs_url="/docs" if settings.ENVIRONMENT != "production" else None,
    redoc_url="/redoc" if settings.ENVIRONMENT != "production" else None,
    lifespan=lifespan,
)

app.add_middleware(SecurityHeadersMiddleware)
app.add_middleware(RequestIDMiddleware)


@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    errors = jsonable_encoder(exc.errors(), custom_encoder={Exception: str})
    log.warning("validation_error", path=request.url.path, errors=errors)
    return JSONResponse(
        status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
        content={"detail": "Validation failed.", "errors": errors},
    )


@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    return JSONResponse(status_code=exc.status_code, content={"detail": exc.detail}, headers=exc.headers)


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception):
    log.error("unhandled_exception", path=request.url.path, error=str(exc), exc_info=True)
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, content={"detail": "Internal server error."}
    )


app.include_router(health.router)
app.include_router(assets.router, prefix=settings.API_V1_PREFIX)
app.include_router(markets.router, prefix=settings.API_V1_PREFIX)
app.include_router(marketdata.router, prefix=settings.API_V1_PREFIX)
